const { Resource } = require('./Resource.js');
const { Operation } = require('./Operation.js');


const { LegalPosition } = require('./LegalPosition.js');
const { Asset } = require('./Asset.js');
const { Event } = require('./Event.js');
const { DataTransfer } = require('./DataTransfer.js');
const { Role } = require('./Role.js');
const { SymboleoContract } = require('./SymboleoContract.js');
const { Obligation } = require('./Obligation.js');
const { Power } = require('./Power.js');
const { Attribute } = require('./Attribute.js');
const { Rule } = require('./Rule.js');
const { LegalSituation } = require('./LegalSituation.js');


console.log('ACPolicy loaded');
process.stdout.write('');

 
class ACPolicy extends Resource{
    constructor(allController) {
        super(allController);
        this._rules = [];
        this._constraints = [];
    }
//------------------------
// INTERFACE
//------------------------


/* Code from template association_GetMany */
getRule(index) {
    let aRule = this._rules[index];
    return aRule;
}

/**
* Relationships
*/

getRules() {
    let newRules = Object.freeze(this._rules);
    return newRules;
    // Or return this.rules
}

numberOfRules() {
    let number = this._rules.length;
    return number;
}

hasRules() {
    let has = this._rules.length > 0;
    return has;
}

indexOfRule(aRule) {
    let index = this.rules.indexOf(aRule); // from the converter
    return index;
 
}

//Utility function 
//AC-not generated by Umple, we use it to search for a rule
findRule(aRule){
    return this._rules.find(obj => obj.decision === aRule.decision && obj.permission === aRule.permission && obj.accessedResource._name === aRule.accessedResource._name && obj.accessedResource._type === aRule.accessedResource._type && obj.accessedRole._name === aRule.accessedRole._name && obj.accessedRole._type === aRule.accessedRole._type);  
}

//AC
 //utlity function 
 //return list of roles
 permissionValid(aAccessedResource, aAccessedRoles, aByRole, aContract) {
  const validRoles = [];

  for (const role of aAccessedRoles) {
    const rule = new Rule('grant', 'read', aAccessedResource, role, aByRole);

    if (((this.hasPermesstion('grant', 'read', aAccessedResource, role, aByRole) ||
    this.hasPermesstionOnLegalPosition('grant','read', aAccessedResource, role, aByRole, aContract)) &&
        this.isValid(rule))) {
      validRoles.push(role.name._value); 
    }
  }

  return validRoles; // flat array with only valid roles
}

//Utility function
//this will create a rule, and search if it exesits in the list of rules
//it should check if he has a rule, if not, it will check if he is the controller, if not
//it will add the rule 
//controller of legalposition can read attribtes of events that part of legal position (pre-authorized)
//controller of operation (pre-authorized)
//controller of legalposition can read Data that part of legal position (pre-authorized)
hasPermesstion(aDecision,aAction, aAccessedResource, aAccessedRole, aByRole){
let aRule = new Rule(aDecision, aAction, aAccessedResource, aAccessedRole,aByRole, this)

if(this.findRule(aRule)){
    return true
  }else{
    
    if(aRule.accessedResource.findController(aRule.accessedRole)){//&& aRule.permission === 'Read'
      
       if(!(aRule.accessedResource instanceof Event) && !(aRule.accessedResource instanceof DataTransfer) && !(aRule.accessedResource instanceof Asset) && !(aRule.accessedResource instanceof Role) ){//aRule.permission === 'Read' &&
      
        return true 
       }else
       {// controller has only read permssition and can give read permission
        if(aRule.permission === 'read')
        return true 
       }
    }// end if for controller
    if(aRule.accessedResource instanceof Asset){
        if(aRule.accessedResource.owner === aRule.accessedRole){
        return true
        }
    }// end if for Asset

    if((aRule.accessedResource instanceof LegalPosition) || (aRule.accessedResource instanceof Event) || (aRule.accessedResource instanceof DataTransfer) || (aRule.accessedResource instanceof Operation)){ //|| (aRule.accessedResource instanceof Operation) 
        // here we could findperformer and find controler cuz it is a lsit
       if(aRule.accessedResource.findPerformer(aRule.accessedRole)) 
       {
        return true
    }
    if(aRule.accessedResource instanceof Obligation){
        if(aRule.accessedResource.findRightHolder(aRule.accessedRole)){//&& aRule.permission === 'Read'
            return true
        }
        if(aRule.accessedResource.findLiable(aRule.accessedRole)){
            return true
        }
    }// end if for obligation
    if(aRule.accessedResource instanceof Power){
        if(aRule.accessedResource.findLiable(aRule.accessedRole)){//&& aRule.permission === 'Read'
            return true
        }
        if(aRule.accessedResource.findRightHolder(aRule.accessedRole)){
            return true
        }
    }// end if for power

    }// end if for instance of legal posiiton, event, operation
    if(aRule.accessedResource instanceof Role){
        if(aRule.accessedResource === aRule.accessedRole ){
           return true
        }
    }// end if for Role
    //if(aRule.accessedResource instanceof SymboleoContract){// use getParty
       // if((aRule.accessedResource.findController(aRule.accessedRole))){
        //    return true
       // }
    //}// end if for Contract 
    return false
  }
}

//AC
hasPermesstionOnLegalPosition(aDecision,aAction, aAccessedResource, aAccessedRole, aByRole, aContract){
  
    
    for (const obligationKey of Object.keys(aContract.obligations)) {
    
      
        if((this.findObject(aContract.obligations[obligationKey].consequent, aAccessedResource) || this.findObject(aContract.obligations[obligationKey].antecedent, aAccessedResource)) &&  aContract.obligations[obligationKey].findPerformer(aAccessedRole)){
            let aRule = new Rule(aDecision, aAction, aContract.obligations[obligationKey], aAccessedRole,aByRole, this)
            return this.isValid(aRule) //check if threre is a constraint that prevent him 
        }
      }
    

    for (const powerKey of Object.keys(aContract.powers)) {
        if((this.findObject(aContract.powers[powerKey].consequent, aAccessedResource) || this.findObject(aContract.powers[powerKey].antecedent, aAccessedResource)) &&  aContract.powers[powerKey].findPerformer(aAccessedRole)){
            let aRule = new Rule(aDecision, aAction, aContract.powers[powerKey], aAccessedRole,aByRole, this)
            return this.isValid(aRule)
        }
      }
    
   return false
}

//AC
findObject (listOfParts, aAccessedResource){
   
    if(typeof listOfParts != 'undefined' &&  listOfParts.length > 0 ){
        switch (aAccessedResource._type.toLowerCase()){
            case 'condition':  
                for(const obj  of  listOfParts){ //.consequentOf
                    if (obj._type === 'Condition' && obj.leftSide === aAccessedResource.leftSide && obj.op ===  aAccessedResource.op && obj.rightSide === aAccessedResource.rightSide) {
                        return true;
                    }}
                break
            case 'statecondition': //here to ackeck state if its of obligation/power if its part of another obligation
                for(const obj  of  listOfParts){ //.consequentOf
                if (obj._type === 'stateCondition' && obj.state === aAccessedResource.state && obj.resource ===  aAccessedResource.resource &&  obj.resourceType === aAccessedResource.resourceType) {
                    return true;
                }}
                break
            case 'eventcondition':
                for(const obj  of  listOfParts){
                if(obj._type === 'eventCondition' && obj.resource === aAccessedResource.partResource && obj.resourceType ===  aAccessedResource.partResourceType){
                    ////console.log("inside if eventconiditon ")
                    return true
                }}
                break
            default:
                return false

        }
    }
    return false;
}
    
/* Code from template association_MinimumNumberOfMethod */
static minimumNumberOfRules() {
    return 0;
}

/* Code from template association_AddManyToOne */
//***use exception instead of boolean to infomr user that they do not have right to access 
//this.aCPolicy.addRulee("grant", "read", this.obligations.delivery, this.assessor, this.seller)
addRulee(aDecision, aPermission, aAccessedResource, aAccessedRole, aByRole) {//aRuleId,
   
    let aRule = new Rule(aDecision, aPermission, aAccessedResource, aAccessedRole, aByRole, this);

    if(aRule != null && ! (typeof aRule === 'undefined')){
       
       if(this.findController(aByRole)){
       
        this.addPolicy(aRule)
      
        
       }else{
     
        this.addRule(aRule) //aRule.setACPolicy(this);
     
       }
    }
    return aRule
}

addRule(aRule) {
    let wasAdded = false;

    //to check if the rule exist, or pre-authrized permesstion. 
    if (this.hasPermesstion(aRule.decision,aRule.permission, aRule.accessedResource, aRule.accessedRole, aRule.byRole)) { //this._rules.includes(aRule) ||
        return false;
    }

    if(this.isValid(aRule)){
        if(this.updateRule(aRule)){
            this._rules.push(aRule);
        }
        
    }

    //if(this.repair(aRule,this._rules)){
       
   
    wasAdded = true;
    return wasAdded;
}

//AC- 
removeRule(aRule) {
    let wasRemoved = false;
    if(this.findRule(aRule)){
        if(aRule.accessedResource.getController().includes())
        this._rules.pop(aRule)
        wasRemoved = true;
    }

      return wasRemoved;

    
}

/* Code from template association_AddIndexControlFunctions */

addRuleAt(aRule, index) {
    let wasAdded = false;
    
    if (this.addRule(aRule)) {
        if (index < 0) { index = 0; }
        if (index > this.numberOfRules()) { index = this.numberOfRules(); }
        
        this._rules.splice(index, 0, aRule);
        wasAdded = true;
    }
    
    return wasAdded;
}

addOrMoveRuleAt(aRule, index) {
    let wasAdded = false;
    
    if (this._rules.includes(aRule)) {
        if (index < 0) { index = 0; }
        if (index > this.numberOfRules()) { index = this.numberOfRules(); }
        
        this._rules.splice(this._rules.indexOf(aRule), 1);
        this._rules.splice(index, 0, aRule);
        wasAdded = true;
    } else {
        wasAdded = this.addRuleAt(aRule, index);
    }
    
    return wasAdded;
}

//Utility function 
//AC-not generated by Umple, we use it to search for a policy
//obj is a pointer like in foreach
findPolicy(aRule){
    return this._constraints.find(obj => obj.decision === aRule.decision && obj.permission === aRule.permission && obj.accessedResource._name === aRule.accessedResource._name && obj.accessedResource._type === aRule.accessedResource._type && obj.accessedRole._name === aRule.accessedRole._name && obj.accessedRole._type === aRule.accessedRole._type);  
}



//Utility function 
//AC-check if the rules does not contain rules that conflict with the policy(constraines)
isValid(aRule){
//isValid 
//check in the policy (constrains), if there is any conflict between the added rule and the constraints 
let isValidVar = true
   
            for (const constraint of this._constraints){
            if(constraint.accessedResource._name === aRule.accessedResource._name && constraint.accessedResource._type === aRule.accessedResource._type && constraint.accessedRole._name === aRule.accessedRole._name && constraint.accessedRole._type === aRule.accessedRole._type)//&& obj.byRole === aRule.byRole
            {
                
                switch (aRule.decision) {
                    case 'grant':
                        switch (aRule.permission) {
                            case 'read':
                                    if((
                                        constraint.decision === 'revoke' && 
                                            (constraint.permission === 'read' || constraint.permission === 'all')) ){
                                        isValidVar = false
                                        return false
                                    }
                                break;
                            case 'write':
                                if((constraint.decision === 'revoke' && 
                                    (constraint.permission === 'write' || constraint.permission === 'all'))||(constraint.decision === 'grant' && constraint.permission === 'read')){
                                        isValidVar = false
                                        return false
                                    }
                                break;
                            case 'all':
                                if((constraint.decision === 'revoke')){
                                    isValidVar = false
                                    return false
                                }
                                break;
                            case 'transfer':
                                if(constraint.decision === 'revoke' && 
                                    (constraint.permission === 'transfer' || constraint.permission === 'all')){
                                    isValidVar = false
                                    return false
                                    }
                                break;
                        }
                        break;
                    case 'revoke':
                        switch (aRule.permission.toLowerCase()) {
                            case 'read':
                                 if(constraint.decision === 'grant' && 
                                    (constraint.permission === 'read' || constraint.permission === 'all' || constraint.permission === 'write' )){
                                        isValidVar = false
                                        return false
                                    }
                                break
                            case 'write':
                                if(constraint.decision === 'grant' && 
                                    (constraint.permission === 'write' || constraint.permission === 'all')){
                                        isValidVar = false
                                        return false
                                    }
                                break;
                            case 'all':
                                if(constraint.decision === 'grant'){
                                    isValidVar = false
                                    return false
                                }
                                break;
                            case 'transfer':
                                 if(constraint.decision === 'grant' && 
                                    (constraint.permission === 'transfer' || constraint.permission === 'all')){
                                        isValidVar = false
                                        return false
                                    }
                                break;
                        }
                        break;
                }// end switch

            }//end if

        };//end forEach //)
        return isValidVar;
    }

//utlity
//AC


//utlity
//Helper function to check if decision is "all" or a specific action
matchesDecision(decision, targetDecision) {
    return decision === 'all' || decision === targetDecision;
}

//AC
//utility function 
//modify permission of constraints according to the new constraints (by controller of policy)
updatePolicy(aRule) {
    let canAdd = true;
    let rulesToRemove = [];
    let rulesToAdd = [];
    //AC 
    for (const constraint of this._constraints) {
        if (constraint.accessedResource._name === aRule.accessedResource._name && constraint.accessedResource._type === aRule.accessedResource._type && constraint.accessedRole._name === aRule.accessedRole._name && constraint.accessedRole._type === aRule.accessedRole._type) {//constraint.accessedResource === aRule.accessedResource && constraint.accessedRole === aRule.accessedRole
            switch (aRule.decision) {
                case 'grant':
                    switch (aRule.permission) {
                        case 'read':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'write' || constraint.permission === 'all') return false;
                                    break;
                                case 'revoke':
                                    if (constraint.permission === 'read') {
                                        //give him back the read permission
                                        constraint.decision = 'grant';
                                        canAdd =  false;
                                        
                                    }
                                    if (constraint.permission === 'all') {
                                        constraint.permission = 'write';
                                        let remainedRule = new Rule('revoke', 'transfer', constraint.accessedResource, constraint.accessedRole, constraint.byRole, this);
                                        rulesToAdd.push(remainedRule)
                                   
                                    }
                                    break;
                            }
                            break;
                        case 'write':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'all') return false;
                                    if (constraint.permission === 'read') {
                                        constraint.permission = 'write';
                                        canAdd =  false;
                                         
                                    }
                                    break;
                                case 'revoke':
                                    if (constraint.permission === 'write') {
                                        constraint.decision = 'grant';
                                        canAdd =  false;
                                        
                                    }
                                    if(constraint.permission === 'read'){
                                        constraint.decision = 'grant'
                                        constraint.permission = 'write'
                                        canAdd =  false
                                        
                                    }
                                    if (constraint.permission === 'all'){
                                        constraint.permission = 'transfer'
                                    
                                    }
                                    break;
                            }
                            break;
                        case 'all':
                            switch (constraint.decision) {
                                case 'grant':
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                        //canAdd =  true
                                        //return
                                    }
                                    break;
                                case 'revoke':
                                    if(constraint.permission === 'all'){
                                    constraint.decision = 'grant';
                                    canAdd =  false;
                                    
                                    }
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                   
                                    }
                                    
                            }
                            break;
                        case 'transfer':
                            switch(constraint.decision)
                            {
                                case 'grant':
                                    if(constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                                case 'revoke':
                                    if(constraint.permission === 'all'){
                                        constraint.permission = 'write'
                                        let remainedRule = new Rule('revoke', 'read', constraint.accessedResource, constraint.accessedRole,constraint.byRole, this);
                                        rulesToAdd.push(remainedRule)
                                   
                                    }
                            }
                            break
                    }
                    break;
                case 'revoke':
                    switch (aRule.permission) {
                        case 'read':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'read' ) {
                                        constraint.decision = 'revoke';
                                        canAdd =  false;
                                        
                                    }
                                    if(constraint.permission === 'all'){
                                        constraint.decision = 'grant'
                                        constraint.permission = 'transfer'
                                        //add revoke read
                                        //canAdd =  true
                                        //eturn
                                    }
                                    if(constraint.permission === 'write'){
                                        constraint.decision = 'revoke'
                                        constraint.permission = 'read'
                                        //add revoke read
                                        canAdd =  false
                                        
                                    }
                                    break;
                                case 'revoke':
                                    if(constraint.permission === 'write' || constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                                    break; // No action needed if already revoked
                            }
                            break;
                        case 'write':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'write') {
                                        constraint.decision = 'revoke';
                                        canAdd =  false;
                                        
                                    }
                                    if(constraint.permission === 'read'){
                                        constraint.permission = 'write'
                                        constraint.decision = 'revoke';
                                        canAdd =  false
                                        
                                    }
                                    if(constraint.permission === 'all'){
                                        constraint.permission = 'transfer'
                                        //canAdd =  true
                                        //return
                                    }
                                    break;
                                case 'revoke':
                                    if(constraint.permission === 'read'){
                                        constraint.permission = 'write'
                                        canAdd =  false
                                        
                                    }
                                    if(constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                                    break; 
                            }
                            break;
                        case 'all':
                            switch (constraint.decision) {
                                case 'grant':
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                        //
                                        //canAdd =  true
                                        //return
                                    }
                                
                                case 'revoke':
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                        //
                                        //canAdd =  true
                                        //return
                                    }
                                    break; 
                            }
                            break;
                        case 'transfer':
                            switch(constraint.decision){
                                case 'grant':
                                    if(constraint.permission === 'transfer'){
                                        constraint.decision = 'revoke'
                                        canAdd =  false
                                        
                                    }
                                    if(constraint.permission === 'all'){
                                        constraint.permission === 'write'
                                        //canAdd =  true
                                        //return
                                    }
                                case 'revoke':
                                    if(constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                            }
                        break
                    }
                    break;
            }
        }
    };//)
    

    // Remove rules marked for deletion
    this._constraints = this._constraints.filter(
        element => !rulesToRemove.includes(element)
    );

    // Add new rules
    rulesToAdd.forEach(rule => this._constraints.push(rule));

    return canAdd;
}

//utlity function 
//AC
//modify permission according to the new rule (by controller of rules)
updateRule(aRule) {
    let canAdd = true;
    let rulesToRemove = [];
    let rulesToAdd = [];
    //this._rules.forEach(constraint => 
    for (const constraint of this._rules)  {
        if (constraint.accessedResource._name === aRule.accessedResource._name && constraint.accessedResource._type === aRule.accessedResource._type && constraint.accessedRole._name === aRule.accessedRole._name && constraint.accessedRole._type === aRule.accessedRole._type) {//constraint.accessedResource === aRule.accessedResource && constraint.accessedRole === aRule.accessedRole
            switch (aRule.decision) {
                case 'grant':
                    switch (aRule.permission) {
                        case 'read':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'write' || constraint.permission === 'all') return false;
                                    break;
                                case 'revoke':
                                    if (constraint.permission === 'read') {
                                        //give him back the read permission
                                        constraint.decision = 'grant';
                                        canAdd =  false;
                                        
                                    }
                                    if (constraint.permission === 'all') {
                                        constraint.permission = 'write';
                                        let remainedRule = new Rule('revoke', 'transfer', constraint.accessedResource, constraint.accessedRole, constraint.byRole, this);
                                        rulesToAdd.push(remainedRule)
                                        //to push the grant read 
                                        //canAdd =  true;
                                        //return 
                                    }
                                    break;
                            }
                            break;
                        case 'write':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'all') return false;
                                    if (constraint.permission === 'read') {
                                        constraint.permission = 'write';
                                        canAdd =  false;
                                         
                                    }
                                    break;
                                case 'revoke':
                                    if (constraint.permission === 'write') {
                                        constraint.decision = 'grant';
                                        canAdd =  false;
                                        
                                    }
                                    if(constraint.permission === 'read'){
                                        constraint.decision = 'grant'
                                        constraint.permission = 'write'
                                        canAdd =  false
                                        
                                    }
                                    if (constraint.permission === 'all'){
                                        constraint.permission = 'transfer'
                                        //add grant write
                                        //canAdd =  true
                                        //return
                                    }
                                    break;
                            }
                            break;
                        case 'all':
                            switch (constraint.decision) {
                                case 'grant':
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                        //canAdd =  true
                                        //return
                                    }
                                    break;
                                case 'revoke':
                                    if(constraint.permission === 'all'){
                                    constraint.decision = 'grant';
                                    canAdd =  false;
                                    
                                    }
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                        //
                                        //canAdd =  true
                                        //return
                                    }
                                    
                            }
                            break;
                        case 'transfer':
                            switch(constraint.decision)
                            {
                                case 'grant':
                                    if(constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                                case 'revoke':
                                    if(constraint.permission === 'all'){
                                        constraint.permission = 'write'
                                        let remainedRule = new Rule('revoke', 'read', constraint.accessedResource, constraint.accessedRole,constraint.byRole, this);
                                        rulesToAdd.push(remainedRule)
                                        //
                                        //canAdd =  true
                                        //return
                                    }
                            }
                            break
                    }
                    break;
                case 'revoke':
                    switch (aRule.permission) {
                        case 'read':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'read' ) {
                                        constraint.decision = 'revoke';
                                        canAdd =  false;
                                        
                                    }else
                                    if(constraint.permission === 'all'){
                                        constraint.decision = 'grant'
                                        constraint.permission = 'transfer'
                                        //add revoke read
                                        //canAdd =  true
                                        //eturn
                                    }else
                                    if(constraint.permission === 'write'){
                                        constraint.decision = 'revoke'
                                        constraint.permission = 'read'
                                        //add revoke read
                                        canAdd =  false
                                        
                                    }
                                    break;
                                case 'revoke':
                                    if(constraint.permission === 'write' || constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                                    break; // No action needed if already revoked
                            }
                            break;
                        case 'write':
                            switch (constraint.decision) {
                                case 'grant':
                                    if (constraint.permission === 'write') {
                                        constraint.decision = 'revoke';
                                        canAdd =  false;
                                        
                                    }
                                    if(constraint.permission === 'read'){
                                        constraint.permission = 'write'
                                        constraint.decision = 'revoke';
                                        canAdd =  false
                                        
                                    }
                                    if(constraint.permission === 'all'){
                                        constraint.permission = 'transfer'
                                        //canAdd =  true
                                        //return
                                    }
                                    break;
                                case 'revoke':
                                    if(constraint.permission === 'read'){
                                        constraint.permission = 'write'
                                        canAdd =  false
                                        
                                    }
                                    if(constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                                    break; 
                            }
                            break;
                        case 'all':
                            switch (constraint.decision) {
                                case 'grant':
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                        //
                                        //canAdd =  true
                                        //return
                                    }
                                
                                case 'revoke':
                                    if(constraint.permission === 'read' || constraint.permission === 'write' || constraint.permission === 'transfer'){
                                        //push to be deleted
                                        rulesToRemove.push(constraint)
                                        //
                                        //canAdd =  true
                                        //return
                                    }
                                    break; 
                            }
                            break;
                        case 'transfer':
                            switch(constraint.decision){
                                case 'grant':
                                    if(constraint.permission === 'transfer'){
                                        constraint.decision = 'revoke'
                                        canAdd =  false
                                        
                                    }
                                    if(constraint.permission === 'all'){
                                        constraint.permission === 'write'
                                        //canAdd =  true
                                        //return
                                    }
                                case 'revoke':
                                    if(constraint.permission === 'all'){
                                        canAdd =  false
                                        
                                    }
                            }
                        break
                    }
                    break;
            }
        }
    }; //)
    

    // Remove rules marked for deletion
    this._rules = this._rules.filter(
        element => !rulesToRemove.includes(element)
    );

    // Add new rules
    //this._constraints = this._constraints.concat(rulesToAdd);
    rulesToAdd.forEach(rule => this._rules.push(rule));

    return canAdd;
}


//Utility function 
//AC-Policies are enforced automatically after every authorization/deauthorization(addRule/deleteRule)
//Constraints
addPolicy(aRule){
    let wasAdded = false;

    //to check if the policy exist
    if (this.findPolicy(aRule) || this.hasPermesstion(aRule.decision,aRule.permission, aRule.accessedResource, aRule.accessedRole, aRule.byRole )) {  //this.hasPermesstion(aRule.decision,aRule.permission, aRule.accessedResource, aRule.accessedRole)
        return false;
    }
   

    // if not exist add it
    if(this.updatePolicy(aRule)){
        ////////console.log("inside addPolicy function")
        ////////console.log(aRule)
        this._constraints.push(aRule);
        ////////console.log("inside addPolicy function2")
        ////////console.log(this._constraints)
    }
    
    wasAdded = true;
    return wasAdded;
}

deletePolicy(){

}


delete() {
    while (this._rules.length > 0) {
        let aRule = this._rules[this._rules.length - 1];
        aRule.delete();
        this._rules.pop();
    }
    
    super.delete();
}



}

module.exports.ACPolicy = ACPolicy;
    
   
